# These are supported funding model platforms

# github: # GitHub Sponsors username
# patreon: # Patreon username
# open_collective: # Open Collective username
# ko_fi: # Ko-fi username
# tidelift: # Tidelift package name
# community_bridge: # Community Bridge project name
# liberapay: # Liberapay username
# issuehunt: # IssueHunt username
# otechie: # Otechie username
# lfx_crowdfunding: # LFX Crowdfunding project name
# custom: # Custom sponsorship URL

# Uncomment and add your funding links above
# For now, users can support by starring and contributing to the project
